backend:
  name: github
  repo: kou029w/intro-to-web-dev
  branch: main
  base_url: https://sveltia-cms-auth.kou029w.workers.dev
media_folder: src/assets
public_folder: /intro-to-web-dev/assets
collections:
  - name: top
    label: トップ・各種ページ
    folder: src
    extension: md
    fields:
      - name: body
        label: 本文
        widget: markdown
  - name: get-started
    label: Web開発入門
    folder: src/get-started
    extension: md
    nested:
      depth: 10
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - name: body
        label: 本文
        widget: markdown
  - name: environment
    label: Web開発環境構築
    folder: src/environment
    extension: md
    nested:
      depth: 10
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - name: body
        label: 本文
        widget: markdown
  - name: js
    label: JavaScript
    folder: src/js
    extension: md
    nested:
      depth: 10
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - name: body
        label: 本文
        widget: markdown
  - name: api
    label: REST APIと非同期処理
    folder: src/api
    extension: md
    nested:
      depth: 10
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - name: body
        label: 本文
        widget: markdown
  - name: hono
    label: Honoハンズオン
    folder: src/hono
    extension: md
    nested:
      depth: 10
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - name: body
        label: 本文
        widget: markdown
  - name: hono-react
    label: Hono + React 連携
    folder: src/hono-react
    extension: md
    nested:
      depth: 10
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - name: body
        label: 本文
        widget: markdown
  - name: sqlite
    label: SQLiteハンズオン
    folder: src/sqlite
    extension: md
    nested:
      depth: 10
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - name: body
        label: 本文
        widget: markdown
  - name: practice
    label: 開発実践
    folder: src/practice
    extension: md
    nested:
      depth: 10
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - name: body
        label: 本文
        widget: markdown
  - name: test
    label: Node.js Test Runnerではじめる自動テスト
    folder: src/test
    extension: md
    nested:
      depth: 10
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - name: body
        label: 本文
        widget: markdown
  - name: web
    label: Web
    folder: src/web
    extension: md
    nested:
      depth: 10
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - name: body
        label: 本文
        widget: markdown
  - name: web-publishing
    label: Webサイトを公開する
    folder: src/web-publishing
    extension: md
    nested:
      depth: 10
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - name: body
        label: 本文
        widget: markdown
  - name: gas-web-app
    label: Google Apps Script (GAS) で作るWebアプリ
    folder: src/gas-web-app
    extension: md
    nested:
      depth: 10
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - name: body
        label: 本文
        widget: markdown
  - name: gas-raspberry-pi
    label: Raspberry Piで温度センサーのデータの送信
    folder: src/gas-raspberry-pi
    extension: md
    nested:
      depth: 10
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - name: body
        label: 本文
        widget: markdown
  - name: ntfy-raspberry-pi
    label: Raspberry Piからスマートフォンにデータを送信する
    folder: src/ntfy-raspberry-pi
    extension: md
    nested:
      depth: 10
    meta:
      path:
        widget: string
        label: Path
        index_file: index
    fields:
      - name: body
        label: 本文
        widget: markdown
